# Generated by Django 3.2.3 on 2021-05-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bancard", "0002_auto_20210516_0143"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="type",
        ),
        migrations.AlterField(
            model_name="transaction",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Gateway response pending"),
                    ("success", "Success"),
                    ("fail", "Fail"),
                    ("reversed", "Reversed"),
                ],
                db_index=True,
                default="pending",
                editable=False,
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
