# Generated by Django 3.2.3 on 2021-05-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bancard", "0003_auto_20210516_1912"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Gateway response pending"),
                            ("success", "Success"),
                            ("fail", "Fail"),
                        ],
                        db_index=True,
                        default="pending",
                        editable=False,
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        default=dict, editable=False, verbose_name="Raw response"
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reversions",
                        to="bancard.transaction",
                        verbose_name="Transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reversion",
                "verbose_name_plural": "Reversions",
            },
        ),
    ]
